name: "Frogbot Scan Pull Request"
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
  security-events: write
jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    environment: frogbot
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JFROG_CLI_LOG_LEVEL: DEBUG
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pip install poetry
      - uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: ""
